name: GitHub Actions for Nuxt.js

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 10.x

    steps:
      - uses: actions/checkout@v1
      - uses: kappa0923/nuxtjs-generate-action@master
