name: GitHub Actions for Nuxt.js

on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 10.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
    - name: generate static web application.
      run: npm run generate
